spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: dev
  servlet:
    multipart:
      # 30MB
      max-file-size: 31457280
      # 30MB
      max-request-size: 31457280